version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data

  middleware:
    build: ./middleware
    ports:
      - 127.0.0.1:6969:6969
    tty: true
